### ISSUE TITLE
feature request: specifying page range

### ISSUE THREAD

**Issue by dsanson** [hac/googlebookdownloader#2]
Great tool. Often I don't want a whole book, but just a few pages, so it would be neat it if was possible to specify a page range.

**Comment by hac** [comment]
Thanks David, I'm on it.

On Mon, Mar 26, 2012 at 7:01 PM, David Sanson <
reply@reply.github.com

> wrote:
> 
> Great tool. Often I don't want a whole book, but just a few pages, so it
> would be neat it if was possible to specify a page range.

**Comment by hac** [comment]
Added: https://github.com/hac/googlebookdownloader/commit/d402934da38f47bdd4b918ae64ef8c8f6aa9d027
